feat: create header, footer and routing
Levosilimo/froggies pull request #2
Opened 2023-01-29 17:30 UTC by anjinsan132131

2023-01-29 17:48 UTC, Levosilimo requested changes

2023-01-29 17:48 UTC, Levosilimo commented on src/constans.ts
> +    linkPath: 'https://github.com/'
Поправь ссылку на https://github.com/solidrules

2023-01-29 17:48 UTC, Levosilimo commented on src/constans.ts
> +    name: 'Lev Silin',
Поправь фамилию на Sylin

2023-01-29 21:07 UTC, Levosilimo approved these changes

2023-01-30 08:04 UTC, SolidRules approved these changes

2023-01-30 19:03 UTC, merged