add component with settings modal window
Levosilimo/froggies pull request #6
Opened 2023-02-05 21:50 UTC by SolidRules

2023-02-05 23:00 UTC, Levosilimo requested changes

2023-02-05 23:00 UTC, Levosilimo commented on src/components/app/app.tsx
> +          <Route path={AppRoute.Settings} element={<SettingsWindow/>}/>
Поп-ап настроек не должен быть частью роутинга

2023-02-05 23:00 UTC, Levosilimo commented on src/pages/settings-page/settings-window.tsx
> +                  className={`language__input ${language ===  'en' ? 'active' : null}`}
null перейдёт в строчное значение 'null'. Тут должна быть пустая строка.

2023-02-05 23:00 UTC, Levosilimo commented on src/pages/settings-page/settings-window.tsx
> +    localStorage.setItem('language', currentLanguage);
Нужно добавить отправку запроса на бек с обновлением языка пользователя ([Update User Data](https://github.com/Levosilimo/rsclone-backend/tree/levosilimo#update-user-data)).
```typescript
async function updateUserData(preferences: UpdateBody): Promise<UpdateBody> {
  const response = await fetch(`${serverURL}/user`, {
    method: 'PATCH',
    body: JSON.stringify(preferences),
    headers: {
      'Content-type': 'application/json',
      'x-access-token': `${token}`,
    },
  });
  const resBody: UpdateBody = await response.json();
  return resBody;
}
updateUserData({language});
```

2023-02-06 21:58 UTC, SolidRules commented on src/components/app/app.tsx
> +          <Route path={AppRoute.Settings} element={<SettingsWindow/>}/>
Убрал Поп-ап из роутинга

2023-02-06 21:59 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +                  className={`language__input ${language ===  'en' ? 'active' : null}`}
Заменил null на пустую строку

2023-02-06 22:00 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +    localStorage.setItem('language', currentLanguage);
Добавил отправку запроса на сервер, но т.к. нет токена приходит респонсе с ошибкой 403. Временно закомментил отправку запроса до решения вопроса с токеном.

2023-02-09 16:01 UTC, Levosilimo requested changes

2023-02-09 16:01 UTC, Levosilimo commented on src/pages/settings-page/settings-window.tsx
> +    language?: "en_us" | "es_es" | "ru" | "uk" | string;
language должен быть string literal type: 
```typescript
 type languages = "en_us" | "es_es" | "ru" | "uk";
 ```
Иначе `| string` нивелирует утверждение того, что какие-то конкретные строки являются допустимыми для этого типа.

```typescript
  const changeLanguage = (e: ChangeEvent) => {
    const currentLanguage = (e.target as HTMLInputElement).value as languages;
    setLanguage(currentLanguage);
    updateUserData({language: currentLanguage});
  }

  type languages = "en_us" | "es_es" | "ru" | "uk";

  interface UpdateBody {
    language?: languages;
    levelFlexbox?: number;
  }
 ```

2023-02-12 10:58 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +    language?: "en_us" | "es_es" | "ru" | "uk" | string;
Поправил типы

2023-02-12 11:21 UTC, Levosilimo approved these changes

2023-02-13 18:22 UTC, anjinsan132131 requested changes
разреши конфликты с дев

2023-02-13 20:30 UTC, anjinsan132131 commented on src/pages/settings-page/settings-window.tsx
> +import { type } from "os";
а зачем этот импорт?

2023-02-13 20:34 UTC, anjinsan132131 requested changes

2023-02-13 20:34 UTC, anjinsan132131 commented on src/pages/settings-page/settings-window.tsx
> +        // 'x-access-token': `${token}`,
а токен разве не нужно в хедер добавлять? это норм, что запрос сейчас падает?

2023-02-13 20:34 UTC, anjinsan132131 commented on src/pages/settings-page/settings-window.tsx
> +        // 'x-access-token': `${token}`,
и сеттинги доступны только для авторизированных пользователей же наверное раз access token нужно передавать на бэк, так? а для не авторизированных тогда может на страницу логина/регистрации перекидывать?

2023-02-15 21:47 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +import { type } from "os";
Не знаю откуда он взялся. Удалил.

2023-02-15 21:47 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +        // 'x-access-token': `${token}`,
На момент разработки не было токена и я закомментил, чтобы не было ошибки. Сейчас поправил.

2023-02-15 21:47 UTC, SolidRules commented on src/pages/settings-page/settings-window.tsx
> +        // 'x-access-token': `${token}`,
Вопрос хороший..Надо отдельно обсудить, но вообще настройку языка, например, желательно оставить и для неавторизованных пользователей.

2023-02-17 19:10 UTC, anjinsan132131 commented on src/constants.ts
> +export const serverURL: string = 'https://rsclone-backend.adaptable.app'
можно не указывать же тип для примитивов, если задано значение

2023-02-17 19:12 UTC, anjinsan132131 approved these changes

2023-02-18 14:14 UTC, merged