feat: add redux store, add logic for redirect to login page, add not …
Levosilimo/froggies pull request #7
Opened 2023-02-08 19:17 UTC by anjinsan132131

…found page, add user auth logic

2023-02-09 15:46 UTC, Levosilimo requested changes

2023-02-09 15:46 UTC, Levosilimo commented on src/components/login/login.tsx
> +        <label className="form-label">E-mail</label>
В запрос [Login User](https://github.com/Levosilimo/rsclone-backend/tree/levosilimo#login-user) в поле логин может поступить как e-mail, так и username пользователя, так как они гарантированно уникальны для каждого пользователя. Проверку на соответствие e-mail regex паттерну лучше убрать, а в label написать просто Login.

2023-02-09 15:46 UTC, Levosilimo commented on src/index.tsx
> +store.dispatch(checkAuthAction());
Думаю, стоит добавить крутилку-preloader пока сайт ждёт ответа на запрос check-auth. Интернет у проверяющих бывает разный, так что их взаимодействие с сайтом до проверки аутентификации может привести к неожиданному поведению.

2023-02-09 15:46 UTC, Levosilimo commented on src/components/app/app.tsx
> +    <HistoryRouter history={browserHistory}>
При переходе аутентифицированных пользователей на Login Page (к примеру, через историю браузера) приложение должно или перебрасывать их на главную страницу, или выкидывать их из аккаунта.

2023-02-12 11:02 UTC, SolidRules approved these changes
С замечаниями Льва согласен. С моей стороны дополнительных замечаний нет.

2023-02-12 14:11 UTC, Levosilimo approved these changes

2023-02-12 14:11 UTC, Levosilimo commented on src/store/user/user-data.ts
>    isDataLoaded: boolean;
Так как переменная принимает значение `true` во время загрузки данных, а не когда они уже загружены, более подходящим названием будет `isDataLoading`

2023-02-12 21:40 UTC, merged